# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv:
  - ".env"
  - "{{.HOME}}/.env"

includes:
  godot-export:
    taskfile: tasks/export/godot.yaml
    internal: true

  butler-task:
    taskfile: tasks/export/butler.yaml
    internal: true

tasks:
  default:
    cmds:
      - task: edit

  edit:
    requires:
      vars:
        - GODOT

    cmds:
      - "{{.GODOT}} -e --path src/ &"

  clean:
    cmds:
      - "rm -rf export/"

  build:
    generates:
      - export/*

    sources:
      - src/**/*

    deps:
      - task: godot-export:export
        vars:
          {
            SRC: "src",
            TARGET: "web",
            OUT_DIR: "export/web/",
            OUT_FILE: "index.html",
          }

  publish:
    sources:
      - src/**/*

    generates:
      - export/**/*

    deps:
      - task: build

    cmds:
      - "cp src/gen/build_info.gd ."

      - defer: "rm build_info.gd"
      - defer: "mv build_info.gd src/gen/build_info.gd"

      - |
        sed -e "s/PLACEHOLDER_GIT_COMMIT/{{git rev-parse HEAD}}/"
            -e "s/PLACEHOLDER_BUILD_TIME/{{date}}/"
        < build_info.gd
        > src/gen/build_info.gd

      - task: butler-task:push
        vars:
          {
            SRC: "export/web/",
            GAME: "SmallConfusion/!ADD GAME NAME!",
            CHANNEL: "html",
          }
