# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv:
  - ".env"
  - "{{.HOME}}/.env"

includes:
  godot-export:
    taskfile: tasks/export/godot.yaml
    internal: true

  butler-task:
    taskfile: tasks/export/butler.yaml
    internal: true

tasks:
  default:
    cmds:
      - task: edit

  edit:
    requires:
      vars:
        - GODOT

    cmds:
      - "{{.GODOT}} -e --path src/"

  clean:
    cmds:
      - "rm -rf export/"

  build:
    generates:
      - export/*

    sources:
      - src/**/*

    vars:
      GIT_COMMIT:
        sh: "git rev-parse HEAD"

    cmds:
      - "cp src/gen/build_info.gd ."

      - defer: "mv build_info.gd src/gen/build_info.gd"

      - |
        sed -i src/gen/build_info.gd \
            -e 's/PLACEHOLDER_GIT_COMMIT/{{.GIT_COMMIT}}/' \
            -e 's/PLACEHOLDER_BUILD_TIME/{{now | date "2006-01-02 15:04:05 MST"}}/'

      - task: godot-export:export
        vars:
          {
            SRC: "src",
            TARGET: "Web",
            OUT_DIR: "{{.ROOT_DIR}}/export/web",
            OUT_FILE: "index.html",
          }

  publish:
    sources:
      - src/**/*

    generates:
      - export/**/*

    deps:
      - task: build
      - task: butler-task:push
        vars:
          {
            SRC: "export/web/",
            GAME: "SmallConfusion/!ADD GAME NAME!",
            CHANNEL: "html",
          }
