# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  MATERIAL_MAKER: '{{default "material-maker" .MATERIAL_MAKER}}'

tasks:
  export:
    requires:
      vars:
        - SRC
        - OUT

    label: "Material Maker export {{.SRC}}"
    sources:
      - "{{.SRC}}"
    generates:
      - "{{.OUT}}"

    cmds: # We have to do this bullshit because godot breaks here.
      - defer: "{{if .EXTRA_FILES}}rm {{.EXTRA_FILES}}{{end}}"
      - |
        expect -c '
          spawn {{.MATERIAL_MAKER}} --export-material -o "{{.GEN_DIR}}" "{{.SRC}}"
          expect "Done"
          sleep 15
          exit
        ' || true
